name = "QDNN"
uuid = "97dc67d0-8bf9-4884-aa4f-e712ebca90f5"
authors = ["Chen Zhao"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
